default_target = "base"

[targets.win."~/.config/mise/config.toml"]
src = "dotfiles/.shared/mise/config.toml"

[targets.win."~/.config/starship.toml"]
src = "dotfiles/win/.config/starship.toml"

[targets.win."~/.gitconfig"]
src = "dotfiles/win/.gitconfig"

[targets.win."~/.wslconfig"]
src = "dotfiles/win/.wslconfig"

[targets.win."~/AppData/Local/lazygit/config.yml"]
src = "dotfiles/win/AppData/Local/lazygit/config.yml"

[targets.win."~/AppData/Roaming/Zellij/config/config.kdl"]
src = "dotfiles/win/AppData/Roaming/Zellij/config/config.kdl"

[targets.win."~/AppData/Roaming/helix/config.toml"]
src = "dotfiles/win/AppData/Roaming/helix/config.toml"

[targets.win."~/AppData/Roaming/jj/config.toml"]
src = "dotfiles/win/AppData/Roaming/jj/config.toml"

[targets.win."~/AppData/Roaming/jjui/config.toml"]
src = "dotfiles/win/AppData/Roaming/jjui/config.toml"

[targets.wsl."~/.bashrc.d/custom.sh"]
src = "dotfiles/wsl/.bashrc.d/custom.sh"

[targets.wsl."~/.codex/AGENTS.md"]
src = "dotfiles/wsl/.codex/AGENTS.md"

[targets.wsl."~/.codex/config.toml"]
src = "dotfiles/wsl/.codex/config.toml"
override = false

[targets.wsl."~/.config/gh/config.yml"]
src = "dotfiles/wsl/.config/gh/config.yml"

[targets.wsl."~/.config/helix/config.toml"]
src = "dotfiles/wsl/.config/helix/config.toml"

[targets.wsl."~/.config/helix/languages.toml"]
src = "dotfiles/wsl/.config/helix/languages.toml"

[targets.wsl."~/.config/jj/config.toml"]
src = "dotfiles/wsl/.config/jj/config.toml"

[targets.wsl."~/.config/mise/config.toml"]
src = "dotfiles/.shared/mise/config.toml"

[targets.wsl."~/.config/opencode/AGENTS.md"]
src = "dotfiles/wsl/.config/opencode/AGENTS.md"

[targets.wsl."~/.config/opencode/opencode.json"]
src = "dotfiles/wsl/.config/opencode/opencode.json"

[targets.wsl."~/.config/starship.toml"]
src = "dotfiles/wsl/.config/starship.toml"

[targets.wsl."~/.config/zellij/config.kdl"]
src = "dotfiles/wsl/.config/zellij/config.kdl"

[targets.wsl."~/.gitconfig"]
src = "dotfiles/wsl/.gitconfig"

[targets.wsl."~/.templates/apm.yml"]
src = "dotfiles/wsl/.templates/apm.yml"
