# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  fedora-check:
    dir: fedora
    cmds:
      - ansible-playbook wsl.yaml --check --diff
    silent: true
  fedora-run:
    dir: fedora
    cmds:
      - ansible-playbook wsl.yaml -v
    silent: true
  ubuntu-check:
    dir: ubuntu
    cmds:
      - ansible-playbook wsl.yaml --check --diff
    silent: true
  ubuntu-run:
    dir: ubuntu
    cmds:
      - ansible-playbook wsl.yaml -v
    silent: true
