- hosts: localhost
  tasks:
    - name: Add user to sudoers
      become: true
      copy:
        dest: "/etc/sudoers.d/{{ user }}"
        content: "{{ user }} ALL=(ALL) NOPASSWD: ALL"
      vars:
        user: lisp719

    - name: Add apt repository
      become: true
      apt_repository:
        repo: ppa:git-core/ppa

    - name: Install apt packages
      become: true
      apt:
        name:
          - fd-find
          - fzf
          - git
          - ranger
        update_cache: yes

    - name: Install homebrew
      shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      args:
        creates: /home/linuxbrew/.linuxbrew/bin/brew

    - name: Install homebrew packages
      homebrew:
        path: /home/linuxbrew/.linuxbrew/bin
        name:
          - gh
          - lazydocker
          - lazygit

    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - ~/.byobu
        - ~/workspace

    - name: Copy files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - src: "{{ playbook_dir }}/settings/.byobu/profile.tmux"
          dest: ~/.byobu/profile.tmux
        - src: "{{ playbook_dir }}/settings/.gitconfig"
          dest: ~/.gitconfig
        - src: "{{ playbook_dir }}/settings/.bashrc"
          dest: ~/.bashrc

    - name: Configure git credential helper
      git_config:
        name: credential.helper
        scope: global
        value: /mnt/c/Program\ Files/Git/mingw64/bin/git-credential-manager-core.exe
