- name: Ensure docker group exists
  become: true
  group:
    name: docker

- name: Add current user to docker group
  become: true
  user:
    name: "{{ ansible_facts['user_id'] }}"
    groups: docker
    append: yes

- name: Install common packages
  become: true
  package:
    name:
      - bubblewrap
      - curl
      - git
      - htop
      - wget
    state: latest

- name: Install mise
  shell: curl https://mise.run | sh
  args:
    creates: ~/.local/bin/mise
