[tools]
apm = { version = "latest", os = ["linux"] }
"aqua:pkgxdev/pkgx" = { version = "latest", os = ["linux"] }
bat = "latest"
codex = "latest"
delta = { version = "latest", os = ["linux"] }
dua = { version = "latest", os = ["linux"] }
eza = "latest"
fd = { version = "latest", os = ["linux"] }
fzf = "latest"
ghq = "latest"
github-cli = "latest"
"github:RivoLink/leaf" = { version = "latest", os = ["linux"] }
gitui = { version = "latest", os = ["linux"] }
helix = "latest"
jj = "latest"
jjui = "latest"
jq = { version = "latest", os = ["linux"] }
lazydocker = { version = "latest", os = ["linux"] }
lazygit = "latest"
micro = "latest"
node = { version = "latest", os = ["linux"] }
"npm:@vtsls/language-server" = { version = "latest", os = ["linux"] }
"npm:pnpm" = { version = "latest", os = ["linux"] }
"npm:prettier" = { version = "latest", os = ["linux"] }
"npm:vscode-langservers-extracted" = { version = "latest", os = ["linux"] }
"npm:yaml-language-server" = { version = "latest", os = ["linux"] }
opencode = { version = "latest", os = ["linux"] }
ripgrep = "latest"
starship = "latest"
task = { version = "latest", os = ["linux"] }
usage = { version = "latest", os = ["linux"] }
xh = { version = "latest", os = ["linux"] }
yazi = "latest"
zellij = "latest"
zoxide = "latest"
