- hosts: localhost
  tasks:
    - name: Add user to sudoers
      become: true
      copy:
        dest: "/etc/sudoers.d/{{ user }}"
        content: "{{ user }} ALL=(ALL) NOPASSWD: ALL"
      vars:
        user: lisp719

    - name: Add apt repository
      become: true
      apt_repository:
        repo: "{{ item }}"
      loop:
        - ppa:git-core/ppa

    - name: Update Installed Packages
      become: true
      apt:
        upgrade: dist
        update_cache: yes

    - name: Copy files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - src: "{{ playbook_dir }}/settings/.bashrc"
          dest: ~/.bashrc

    - import_tasks: ../tasks/common.yaml
