[tools]
apm = "latest"
"aqua:pkgxdev/pkgx" = { version = "latest", os = ["linux"] }
bat = "latest"
codex = "latest"
delta = "latest"
dua = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
ghq = "latest"
github-cli = "latest"
"github:RivoLink/leaf" = "latest"
"github:mogurastore/mdots" = "latest"
"github:zyedidia/eget" = "latest"
gitui = "latest"
helix = "latest"
herdr = "latest"
hunk = "latest"
jj = "latest"
jjui = "latest"
jq = "latest"
lazydocker = "latest"
lazygit = "latest"
micro = "latest"
node = { version = "latest", os = ["linux"] }
"npm:@vtsls/language-server" = { version = "latest", os = ["linux"] }
"npm:prettier" = { version = "latest", os = ["linux"] }
"npm:vscode-langservers-extracted" = { version = "latest", os = ["linux"] }
"npm:yaml-language-server" = { version = "latest", os = ["linux"] }
opencode = "latest"
pnpm = { version = "latest", os = ["linux"] }
ripgrep = "latest"
starship = "latest"
taplo = "latest"
task = "latest"
usage = "latest"
xh = "latest"
yazi = "latest"
zellij = "latest"
zoxide = "latest"
