[tools]
bat = "latest"
eza = "latest"
fzf = "latest"
ghq = "latest"
helix = "latest"
jj = "latest"
jjui = "latest"
lazygit = "latest"
starship = "latest"
yazi = "latest"
zellij = "latest"
zoxide = "latest"
rg = "latest"
