[tools]
apm = "latest"
"aqua:pkgxdev/pkgx" = "latest"
bat = "latest"
delta = "latest"
dua = "latest"
fd = "latest"
fzf = "latest"
ghq = "latest"
github-cli = "latest"
"github:RivoLink/leaf" = "latest"
gitui = "latest"
helix = "latest"
jj = "latest"
jjui = "latest"
jq = "latest"
lazydocker = "latest"
lazygit = "latest"
node = "latest"
"npm:@vtsls/language-server" = "latest"
"npm:pnpm" = "latest"
"npm:prettier" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:yaml-language-server" = "latest"
opencode = "latest"
ripgrep = "latest"
starship = "latest"
task = "latest"
usage = "latest"
xh = "latest"
yazi = "latest"
zellij = "latest"
zoxide = "latest"
