[tools]
bat = "latest"
delta = "latest"
dua = "latest"
fd = "latest"
fzf = "latest"
ghq = "latest"
github-cli = "latest"
gitui = "latest"
helix = "latest"
jj = "latest"
lazydocker = "latest"
lazygit = "latest"
node = "latest"
"npm:@rivolink/leaf" = { version = "latest", allow_low_downloads = true }
"npm:@vtsls/language-server" = "latest"
"npm:pnpm" = "latest"
"npm:prettier" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:yaml-language-server" = "latest"
opencode = "latest"
ripgrep = "latest"
starship = "latest"
task = "latest"
usage = "latest"
yazi = "latest"
zellij = "latest"
zoxide = "latest"
