- hosts: localhost
  tasks:
    - name: Update Installed Packages
      become: true
      dnf:
        name: "*"
        state: latest
        update_cache: yes

    - name: Install dnf packages
      become: true
      dnf:
        name:
          - "@development-tools"
        state: latest
        update_cache: yes

    - import_tasks: ../tasks/wsl_common.yaml
